#name of the flow 
name: Django CI

#the trigger for the workflow
on:
  push:
  pull_request:


#what the workflow will do
jobs:
  build:
    #the server to run the job on
    runs-on: ubuntu-latest
    #commands to run in terminal 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    #set up python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    #install dependencies like requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    #linting with flake8    
    - name: Run Flake8
      run: flake8 .



    #run django checks
    - name: Validate Django
      run: python manage.py check

    #end of the flow
    - name: end the flow
      run: echo "Django CI Completed Successfully"

